/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
    colors: {
      'color-static-surface-nested': 'var(--clr-static-surface-nested)',
      'color-static-surface-default': 'var(--clr-static-surface-default)',
      'color-static-surface-raised': 'var(--clr-static-surface-raised)',
      'color-static-surface-elevated': 'var(--clr-static-surface-elevated)',
      'color-static-surface-scrim': 'var(--clr-static-surface-scrim)',
      'color-static-surface-inverse-nested':
        'var(--clr-static-surface-inverse-nested)',
      'color-static-surface-inverse-default':
        'var(--clr-static-surface-inverse-default)',
      'color-static-surface-inverse-raised':
        'var(--clr-static-surface-inverse-raised)',
      'color-static-surface-inverse-elevated':
        'var(--clr-static-surface-inverse-elevated)',
      'color-static-surface-inverse-scrim':
        'var(--clr-static-surface-inverse-scrim)',
      'color-static-surface-sentiment-informative':
        'var(--clr-static-surface-sentiment-informative)',
      'color-static-surface-sentiment-neutral':
        'var(--clr-static-surface-sentiment-neutral)',
      'color-static-surface-sentiment-positive':
        'var(--clr-static-surface-sentiment-positive)',
      'color-static-surface-sentiment-caution':
        'var(--clr-static-surface-sentiment-caution)',
      'color-static-surface-sentiment-negative':
        'var(--clr-static-surface-sentiment-negative)',
      'color-static-surface-sentiment-inverse-informative':
        'var(--clr-static-surface-sentiment-inverse-informative)',
      'color-static-surface-sentiment-inverse-neutral':
        'var(--clr-static-surface-sentiment-inverse-neutral)',
      'color-static-surface-sentiment-inverse-positive':
        'var(--clr-static-surface-sentiment-inverse-positive)',
      'color-static-surface-sentiment-inverse-caution':
        'var(--clr-static-surface-sentiment-inverse-caution)',
      'color-static-surface-sentiment-inverse-negative':
        'var(--clr-static-surface-sentiment-inverse-negative)',
      'color-static-content-strong': 'var(--clr-static-content-strong)',
      'color-static-content-default': 'var(--clr-static-content-default)',
      'color-static-content-moderate': 'var(--clr-static-content-moderate)',
      'color-static-content-weak': 'var(--clr-static-content-weak)',
      'color-static-content-inverse-strong':
        'var(--clr-static-content-inverse-strong)',
      'color-static-content-inverse-default':
        'var(--clr-static-content-inverse-default)',
      'color-static-content-inverse-moderate':
        'var(--clr-static-content-inverse-moderate)',
      'color-static-content-inverse-weak':
        'var(--clr-static-content-inverse-weak)',
      'color-static-content-sentiment-informative':
        'var(--clr-static-content-sentiment-informative)',
      'color-static-content-sentiment-neutral':
        'var(--clr-static-content-sentiment-neutral)',
      'color-static-content-sentiment-positive':
        'var(--clr-static-content-sentiment-positive)',
      'color-static-content-sentiment-caution':
        'var(--clr-static-content-sentiment-caution)',
      'color-static-content-sentiment-negative':
        'var(--clr-static-content-sentiment-negative)',
      'color-static-content-sentiment-inverse-informative':
        'var(--clr-static-content-sentiment-inverse-informative)',
      'color-static-content-sentiment-inverse-neutral':
        'var(--clr-static-content-sentiment-inverse-neutral)',
      'color-static-content-sentiment-inverse-positive':
        'var(--clr-static-content-sentiment-inverse-positive)',
      'color-static-content-sentiment-inverse-caution':
        'var(--clr-static-content-sentiment-inverse-caution)',
      'color-static-content-sentiment-inverse-negative':
        'var(--clr-static-content-sentiment-inverse-negative)',
      'color-static-divider-weak': 'var(--clr-static-divider-weak)',
      'color-static-divider-default': 'var(--clr-static-divider-default)',
      'color-static-divider-strong': 'var(--clr-static-divider-strong)',
      'color-static-divider-inverse-weak':
        'var(--clr-static-divider-inverse-weak)',
      'color-static-divider-inverse-default':
        'var(--clr-static-divider-inverse-default)',
      'color-static-divider-inverse-strong':
        'var(--clr-static-divider-inverse-strong)',
      'color-static-divider-sentiment-informative':
        'var(--clr-static-divider-sentiment-informative)',
      'color-static-divider-sentiment-neutral':
        'var(--clr-static-divider-sentiment-neutral)',
      'color-static-divider-sentiment-positive':
        'var(--clr-static-divider-sentiment-positive)',
      'color-static-divider-sentiment-caution':
        'var(--clr-static-divider-sentiment-caution)',
      'color-static-divider-sentiment-negative':
        'var(--clr-static-divider-sentiment-negative)',
      'color-iactive-fill-primary-enabled':
        'var(--clr-iactive-fill-primary-enabled)',
      'color-iactive-fill-primary-hover':
        'var(--clr-iactive-fill-primary-hover)',
      'color-iactive-fill-primary-pressed':
        'var(--clr-iactive-fill-primary-pressed)',
      'color-iactive-fill-primary-disabled':
        'var(--clr-iactive-fill-primary-disabled)',
      'color-iactive-fill-primary-on-enabled':
        'var(--clr-iactive-fill-primary-on-enabled)',
      'color-iactive-fill-primary-on-disabled':
        'var(--clr-iactive-fill-primary-on-disabled)',
      'color-iactive-fill-primary-text': 'var(--clr-iactive-fill-primary-text)',
      'color-iactive-fill-secondary-enabled':
        'var(--clr-iactive-fill-secondary-enabled)',
      'color-iactive-fill-secondary-hover':
        'var(--clr-iactive-fill-secondary-hover)',
      'color-iactive-fill-secondary-pressed':
        'var(--clr-iactive-fill-secondary-pressed)',
      'color-iactive-fill-secondary-disabled':
        'var(--clr-iactive-fill-secondary-disabled)',
      'color-iactive-fill-secondary-on-enabled':
        'var(--clr-iactive-fill-secondary-on-enabled)',
      'color-iactive-fill-secondary-on-disabled':
        'var(--clr-iactive-fill-secondary-on-disabled)',
      'color-iactive-fill-secondary-text':
        'var(--clr-iactive-fill-secondary-text)',
      'color-iactive-fill-inverse-enabled':
        'var(--clr-iactive-fill-inverse-enabled)',
      'color-iactive-fill-inverse-hover':
        'var(--clr-iactive-fill-inverse-hover)',
      'color-iactive-fill-inverse-pressed':
        'var(--clr-iactive-fill-inverse-pressed)',
      'color-iactive-fill-inverse-disabled':
        'var(--clr-iactive-fill-inverse-disabled)',
      'color-iactive-fill-inverse-on-enabled':
        'var(--clr-iactive-fill-inverse-on-enabled)',
      'color-iactive-fill-inverse-on-disabled':
        'var(--clr-iactive-fill-inverse-on-disabled)',
      'color-iactive-fill-inverse-text': 'var(--clr-iactive-fill-inverse-text)',
      'color-iactive-fill-negative-enabled':
        'var(--clr-iactive-fill-negative-enabled)',
      'color-iactive-fill-negative-hover':
        'var(--clr-iactive-fill-negative-hover)',
      'color-iactive-fill-negative-pressed':
        'var(--clr-iactive-fill-negative-pressed)',
      'color-iactive-fill-negative-disabled':
        'var(--clr-iactive-fill-negative-disabled)',
      'color-iactive-fill-negative-on-enabled':
        'var(--clr-iactive-fill-negative-on-enabled)',
      'color-iactive-fill-negative-on-disabled':
        'var(--clr-iactive-fill-negative-on-disabled)',
      'color-iactive-fill-negative-text':
        'var(--clr-iactive-fill-negative-text)',
      'color-iactive-fill-utility-selected':
        'var(--clr-iactive-fill-utility-selected)',
      'color-iactive-fill-utility-on-selected':
        'var(--clr-iactive-fill-utility-on-selected)',
      'color-iactive-fill-utility-input':
        'var(--clr-iactive-fill-utility-input)',
      'color-iactive-fill-caution-enabled':
        'var(--clr-iactive-fill-caution-enabled)',
      'color-iactive-outline-primary-enabled':
        'var(--clr-iactive-outline-primary-enabled)',
      'color-iactive-outline-primary-hover':
        'var(--clr-iactive-outline-primary-hover)',
      'color-iactive-outline-primary-pressed':
        'var(--clr-iactive-outline-primary-pressed)',
      'color-iactive-outline-primary-disabled':
        'var(--clr-iactive-outline-primary-disabled)',
      'color-iactive-outline-primary-selected-enabled':
        'var(--clr-iactive-outline-primary-selected-enabled)',
      'color-iactive-outline-primary-selected-hover':
        'var(--clr-iactive-outline-primary-selected-hover)',
      'color-iactive-outline-primary-selected-pressed':
        'var(--clr-iactive-outline-primary-selected-pressed)',
      'color-iactive-outline-secondary-enabled':
        'var(--clr-iactive-outline-secondary-enabled)',
      'color-iactive-outline-secondary-hover':
        'var(--clr-iactive-outline-secondary-hover)',
      'color-iactive-outline-secondary-pressed':
        'var(--clr-iactive-outline-secondary-pressed)',
      'color-iactive-outline-secondary-disabled':
        'var(--clr-iactive-outline-secondary-disabled)',
      'color-iactive-outline-secondary-selected-enabled':
        'var(--clr-iactive-outline-secondary-selected-enabled)',
      'color-iactive-outline-secondary-selected-hover':
        'var(--clr-iactive-outline-secondary-selected-hover)',
      'color-iactive-outline-secondary-selected-pressed':
        'var(--clr-iactive-outline-secondary-selected-pressed)',
      'color-iactive-outline-inverse-enabled':
        'var(--clr-iactive-outline-inverse-enabled)',
      'color-iactive-outline-inverse-hover':
        'var(--clr-iactive-outline-inverse-hover)',
      'color-iactive-outline-inverse-pressed':
        'var(--clr-iactive-outline-inverse-pressed)',
      'color-iactive-outline-inverse-disabled':
        'var(--clr-iactive-outline-inverse-disabled)',
      'color-iactive-outline-inverse-selected-enabled':
        'var(--clr-iactive-outline-inverse-selected-enabled)',
      'color-iactive-outline-inverse-selected-hover':
        'var(--clr-iactive-outline-inverse-selected-hover)',
      'color-iactive-outline-inverse-selected-pressed':
        'var(--clr-iactive-outline-inverse-selected-pressed)',
      'color-iactive-outline-negative-enabled':
        'var(--clr-iactive-outline-negative-enabled)',
      'color-iactive-outline-negative-hover':
        'var(--clr-iactive-outline-negative-hover)',
      'color-iactive-outline-negative-pressed':
        'var(--clr-iactive-outline-negative-pressed)',
      'color-iactive-outline-negative-disabled':
        'var(--clr-iactive-outline-negative-disabled)',
      'color-iactive-outline-negative-selected-enabled':
        'var(--clr-iactive-outline-negative-selected-enabled)',
      'color-iactive-outline-negative-selected-hover':
        'var(--clr-iactive-outline-negative-selected-hover)',
      'color-iactive-outline-negative-selected-pressed':
        'var(--clr-iactive-outline-negative-selected-pressed)',
      'color-iactive-overlay-primary-enabled':
        'var(--clr-iactive-overlay-primary-enabled)',
      'color-iactive-overlay-primary-hover':
        'var(--clr-iactive-overlay-primary-hover)',
      'color-iactive-overlay-primary-pressed':
        'var(--clr-iactive-overlay-primary-pressed)',
      'color-iactive-overlay-primary-disabled':
        'var(--clr-iactive-overlay-primary-disabled)',
      'color-iactive-overlay-primary-selected-enabled':
        'var(--clr-iactive-overlay-primary-selected-enabled)',
      'color-iactive-overlay-primary-selected-hover':
        'var(--clr-iactive-overlay-primary-selected-hover)',
      'color-iactive-overlay-primary-selected-pressed':
        'var(--clr-iactive-overlay-primary-selected-pressed)',
      'color-iactive-overlay-Secondary-enabled':
        'var(--clr-iactive-overlay-Secondary-enabled)',
      'color-iactive-overlay-Secondary-hover':
        'var(--clr-iactive-overlay-Secondary-hover)',
      'color-iactive-overlay-Secondary-pressed':
        'var(--clr-iactive-overlay-Secondary-pressed)',
      'color-iactive-overlay-Secondary-disabled':
        'var(--clr-iactive-overlay-Secondary-disabled)',
      'color-iactive-overlay-secondary-selected-enabled':
        'var(--clr-iactive-overlay-secondary-selected-enabled)',
      'color-iactive-overlay-secondary-selected-hover':
        'var(--clr-iactive-overlay-secondary-selected-hover)',
      'color-iactive-overlay-secondary-selected-pressed':
        'var(--clr-iactive-overlay-secondary-selected-pressed)',
      'color-iactive-overlay-negative-enabled':
        'var(--clr-iactive-overlay-negative-enabled)',
      'color-iactive-overlay-negative-hover':
        'var(--clr-iactive-overlay-negative-hover)',
      'color-iactive-overlay-negative-pressed':
        'var(--clr-iactive-overlay-negative-pressed)',
      'color-iactive-overlay-negative-disabled':
        'var(--clr-iactive-overlay-negative-disabled)',
      'color-iactive-overlay-negative-selected-enabled':
        'var(--clr-iactive-overlay-negative-selected-enabled)',
      'color-iactive-overlay-negative-selected-hover':
        'var(--clr-iactive-overlay-negative-selected-hover)',
      'color-iactive-overlay-negative-selected-pressed':
        'var(--clr-iactive-overlay-negative-selected-pressed)',
      'color-iactive-overlay-inverse-enabled':
        'var(--clr-iactive-overlay-inverse-enabled)',
      'color-iactive-overlay-inverse-hover':
        'var(--clr-iactive-overlay-inverse-hover)',
      'color-iactive-overlay-inverse-pressed':
        'var(--clr-iactive-overlay-inverse-pressed)',
      'color-iactive-overlay-inverse-selected-enabled':
        'var(--clr-iactive-overlay-inverse-selected-enabled)',
      'color-iactive-overlay-inverse-selected-hover':
        'var(--clr-iactive-overlay-inverse-selected-hover)',
      'color-iactive-overlay-inverse-selected-pressed':
        'var(--clr-iactive-overlay-inverse-selected-pressed)',
      'color-static-surface-nested': 'var(--clr-static-surface-nested)',
      'color-static-surface-default': 'var(--clr-static-surface-default)',
      'color-static-surface-raised': 'var(--clr-static-surface-raised)',
      'color-static-surface-elevated': 'var(--clr-static-surface-elevated)',
      'color-static-surface-scrim': 'var(--clr-static-surface-scrim)',
      'color-static-surface-inverse-nested':
        'var(--clr-static-surface-inverse-nested)',
      'color-static-surface-inverse-default':
        'var(--clr-static-surface-inverse-default)',
      'color-static-surface-inverse-raised':
        'var(--clr-static-surface-inverse-raised)',
      'color-static-surface-inverse-elevated':
        'var(--clr-static-surface-inverse-elevated)',
      'color-static-surface-inverse-scrim':
        'var(--clr-static-surface-inverse-scrim)',
      'color-static-surface-sentiment-informative':
        'var(--clr-static-surface-sentiment-informative)',
      'color-static-surface-sentiment-neutral':
        'var(--clr-static-surface-sentiment-neutral)',
      'color-static-surface-sentiment-positive':
        'var(--clr-static-surface-sentiment-positive)',
      'color-static-surface-sentiment-caution':
        'var(--clr-static-surface-sentiment-caution)',
      'color-static-surface-sentiment-negative':
        'var(--clr-static-surface-sentiment-negative)',
      'color-static-surface-sentiment-inverse-informative':
        'var(--clr-static-surface-sentiment-inverse-informative)',
      'color-static-surface-sentiment-inverse-neutral':
        'var(--clr-static-surface-sentiment-inverse-neutral)',
      'color-static-surface-sentiment-inverse-positive':
        'var(--clr-static-surface-sentiment-inverse-positive)',
      'color-static-surface-sentiment-inverse-caution':
        'var(--clr-static-surface-sentiment-inverse-caution)',
      'color-static-surface-sentiment-inverse-negative':
        'var(--clr-static-surface-sentiment-inverse-negative)',
      'color-static-content-strong': 'var(--clr-static-content-strong)',
      'color-static-content-default': 'var(--clr-static-content-default)',
      'color-static-content-moderate': 'var(--clr-static-content-moderate)',
      'color-static-content-weak': 'var(--clr-static-content-weak)',
      'color-static-content-inverse-strong':
        'var(--clr-static-content-inverse-strong)',
      'color-static-content-inverse-default':
        'var(--clr-static-content-inverse-default)',
      'color-static-content-inverse-moderate':
        'var(--clr-static-content-inverse-moderate)',
      'color-static-content-inverse-weak':
        'var(--clr-static-content-inverse-weak)',
      'color-static-content-sentiment-informative':
        'var(--clr-static-content-sentiment-informative)',
      'color-static-content-sentiment-neutral':
        'var(--clr-static-content-sentiment-neutral)',
      'color-static-content-sentiment-positive':
        'var(--clr-static-content-sentiment-positive)',
      'color-static-content-sentiment-caution':
        'var(--clr-static-content-sentiment-caution)',
      'color-static-content-sentiment-negative':
        'var(--clr-static-content-sentiment-negative)',
      'color-static-content-sentiment-inverse-informative':
        'var(--clr-static-content-sentiment-inverse-informative)',
      'color-static-content-sentiment-inverse-neutral':
        'var(--clr-static-content-sentiment-inverse-neutral)',
      'color-static-content-sentiment-inverse-positive':
        'var(--clr-static-content-sentiment-inverse-positive)',
      'color-static-content-sentiment-inverse-caution':
        'var(--clr-static-content-sentiment-inverse-caution)',
      'color-static-content-sentiment-inverse-negative':
        'var(--clr-static-content-sentiment-inverse-negative)',
      'color-static-divider-weak': 'var(--clr-static-divider-weak)',
      'color-static-divider-default': 'var(--clr-static-divider-default)',
      'color-static-divider-strong': 'var(--clr-static-divider-strong)',
      'color-static-divider-inverse-weak':
        'var(--clr-static-divider-inverse-weak)',
      'color-static-divider-inverse-default':
        'var(--clr-static-divider-inverse-default)',
      'color-static-divider-inverse-strong':
        'var(--clr-static-divider-inverse-strong)',
      'color-static-divider-sentiment-informative':
        'var(--clr-static-divider-sentiment-informative)',
      'color-static-divider-sentiment-neutral':
        'var(--clr-static-divider-sentiment-neutral)',
      'color-static-divider-sentiment-positive':
        'var(--clr-static-divider-sentiment-positive)',
      'color-static-divider-sentiment-caution':
        'var(--clr-static-divider-sentiment-caution)',
      'color-static-divider-sentiment-negative':
        'var(--clr-static-divider-sentiment-negative)',
      'color-iactive-fill-primary-enabled':
        'var(--clr-iactive-fill-primary-enabled)',
      'color-iactive-fill-primary-hover':
        'var(--clr-iactive-fill-primary-hover)',
      'color-iactive-fill-primary-pressed':
        'var(--clr-iactive-fill-primary-pressed)',
      'color-iactive-fill-primary-disabled':
        'var(--clr-iactive-fill-primary-disabled)',
      'color-iactive-fill-primary-on-enabled':
        'var(--clr-iactive-fill-primary-on-enabled)',
      'color-iactive-fill-primary-on-disabled':
        'var(--clr-iactive-fill-primary-on-disabled)',
      'color-iactive-fill-primary-text': 'var(--clr-iactive-fill-primary-text)',
      'color-iactive-fill-secondary-enabled':
        'var(--clr-iactive-fill-secondary-enabled)',
      'color-iactive-fill-secondary-hover':
        'var(--clr-iactive-fill-secondary-hover)',
      'color-iactive-fill-secondary-pressed':
        'var(--clr-iactive-fill-secondary-pressed)',
      'color-iactive-fill-secondary-disabled':
        'var(--clr-iactive-fill-secondary-disabled)',
      'color-iactive-fill-secondary-on-enabled':
        'var(--clr-iactive-fill-secondary-on-enabled)',
      'color-iactive-fill-secondary-on-disabled':
        'var(--clr-iactive-fill-secondary-on-disabled)',
      'color-iactive-fill-secondary-text':
        'var(--clr-iactive-fill-secondary-text)',
      'color-iactive-fill-inverse-enabled':
        'var(--clr-iactive-fill-inverse-enabled)',
      'color-iactive-fill-inverse-hover':
        'var(--clr-iactive-fill-inverse-hover)',
      'color-iactive-fill-inverse-pressed':
        'var(--clr-iactive-fill-inverse-pressed)',
      'color-iactive-fill-inverse-disabled':
        'var(--clr-iactive-fill-inverse-disabled)',
      'color-iactive-fill-inverse-on-enabled':
        'var(--clr-iactive-fill-inverse-on-enabled)',
      'color-iactive-fill-inverse-on-disabled':
        'var(--clr-iactive-fill-inverse-on-disabled)',
      'color-iactive-fill-inverse-text': 'var(--clr-iactive-fill-inverse-text)',
      'color-iactive-fill-negative-enabled':
        'var(--clr-iactive-fill-negative-enabled)',
      'color-iactive-fill-negative-hover':
        'var(--clr-iactive-fill-negative-hover)',
      'color-iactive-fill-negative-pressed':
        'var(--clr-iactive-fill-negative-pressed)',
      'color-iactive-fill-negative-disabled':
        'var(--clr-iactive-fill-negative-disabled)',
      'color-iactive-fill-negative-on-enabled':
        'var(--clr-iactive-fill-negative-on-enabled)',
      'color-iactive-fill-negative-on-disabled':
        'var(--clr-iactive-fill-negative-on-disabled)',
      'color-iactive-fill-negative-text':
        'var(--clr-iactive-fill-negative-text)',
      'color-iactive-fill-utility-selected':
        'var(--clr-iactive-fill-utility-selected)',
      'color-iactive-fill-utility-on-selected':
        'var(--clr-iactive-fill-utility-on-selected)',
      'color-iactive-fill-utility-input':
        'var(--clr-iactive-fill-utility-input)',
      'color-iactive-fill-caution-enabled':
        'var(--clr-iactive-fill-caution-enabled)',
      'color-iactive-outline-primary-enabled':
        'var(--clr-iactive-outline-primary-enabled)',
      'color-iactive-outline-primary-hover':
        'var(--clr-iactive-outline-primary-hover)',
      'color-iactive-outline-primary-pressed':
        'var(--clr-iactive-outline-primary-pressed)',
      'color-iactive-outline-primary-disabled':
        'var(--clr-iactive-outline-primary-disabled)',
      'color-iactive-outline-primary-selected-enabled':
        'var(--clr-iactive-outline-primary-selected-enabled)',
      'color-iactive-outline-primary-selected-hover':
        'var(--clr-iactive-outline-primary-selected-hover)',
      'color-iactive-outline-primary-selected-pressed':
        'var(--clr-iactive-outline-primary-selected-pressed)',
      'color-iactive-outline-secondary-enabled':
        'var(--clr-iactive-outline-secondary-enabled)',
      'color-iactive-outline-secondary-hover':
        'var(--clr-iactive-outline-secondary-hover)',
      'color-iactive-outline-secondary-pressed':
        'var(--clr-iactive-outline-secondary-pressed)',
      'color-iactive-outline-secondary-disabled':
        'var(--clr-iactive-outline-secondary-disabled)',
      'color-iactive-outline-secondary-selected-enabled':
        'var(--clr-iactive-outline-secondary-selected-enabled)',
      'color-iactive-outline-secondary-selected-hover':
        'var(--clr-iactive-outline-secondary-selected-hover)',
      'color-iactive-outline-secondary-selected-pressed':
        'var(--clr-iactive-outline-secondary-selected-pressed)',
      'color-iactive-outline-inverse-enabled':
        'var(--clr-iactive-outline-inverse-enabled)',
      'color-iactive-outline-inverse-hover':
        'var(--clr-iactive-outline-inverse-hover)',
      'color-iactive-outline-inverse-pressed':
        'var(--clr-iactive-outline-inverse-pressed)',
      'color-iactive-outline-inverse-disabled':
        'var(--clr-iactive-outline-inverse-disabled)',
      'color-iactive-outline-inverse-selected-enabled':
        'var(--clr-iactive-outline-inverse-selected-enabled)',
      'color-iactive-outline-inverse-selected-hover':
        'var(--clr-iactive-outline-inverse-selected-hover)',
      'color-iactive-outline-inverse-selected-pressed':
        'var(--clr-iactive-outline-inverse-selected-pressed)',
      'color-iactive-outline-negative-enabled':
        'var(--clr-iactive-outline-negative-enabled)',
      'color-iactive-outline-negative-hover':
        'var(--clr-iactive-outline-negative-hover)',
      'color-iactive-outline-negative-pressed':
        'var(--clr-iactive-outline-negative-pressed)',
      'color-iactive-outline-negative-disabled':
        'var(--clr-iactive-outline-negative-disabled)',
      'color-iactive-outline-negative-selected-enabled':
        'var(--clr-iactive-outline-negative-selected-enabled)',
      'color-iactive-outline-negative-selected-hover':
        'var(--clr-iactive-outline-negative-selected-hover)',
      'color-iactive-outline-negative-selected-pressed':
        'var(--clr-iactive-outline-negative-selected-pressed)',
      'color-iactive-overlay-primary-enabled':
        'var(--clr-iactive-overlay-primary-enabled)',
      'color-iactive-overlay-primary-hover':
        'var(--clr-iactive-overlay-primary-hover)',
      'color-iactive-overlay-primary-pressed':
        'var(--clr-iactive-overlay-primary-pressed)',
      'color-iactive-overlay-primary-disabled':
        'var(--clr-iactive-overlay-primary-disabled)',
      'color-iactive-overlay-primary-selected-enabled':
        'var(--clr-iactive-overlay-primary-selected-enabled)',
      'color-iactive-overlay-primary-selected-hover':
        'var(--clr-iactive-overlay-primary-selected-hover)',
      'color-iactive-overlay-primary-selected-pressed':
        'var(--clr-iactive-overlay-primary-selected-pressed)',
      'color-iactive-overlay-Secondary-enabled':
        'var(--clr-iactive-overlay-Secondary-enabled)',
      'color-iactive-overlay-Secondary-hover':
        'var(--clr-iactive-overlay-Secondary-hover)',
      'color-iactive-overlay-Secondary-pressed':
        'var(--clr-iactive-overlay-Secondary-pressed)',
      'color-iactive-overlay-Secondary-disabled':
        'var(--clr-iactive-overlay-Secondary-disabled)',
      'color-iactive-overlay-secondary-selected-enabled':
        'var(--clr-iactive-overlay-secondary-selected-enabled)',
      'color-iactive-overlay-secondary-selected-hover':
        'var(--clr-iactive-overlay-secondary-selected-hover)',
      'color-iactive-overlay-secondary-selected-pressed':
        'var(--clr-iactive-overlay-secondary-selected-pressed)',
      'color-iactive-overlay-negative-enabled':
        'var(--clr-iactive-overlay-negative-enabled)',
      'color-iactive-overlay-negative-hover':
        'var(--clr-iactive-overlay-negative-hover)',
      'color-iactive-overlay-negative-pressed':
        'var(--clr-iactive-overlay-negative-pressed)',
      'color-iactive-overlay-negative-disabled':
        'var(--clr-iactive-overlay-negative-disabled)',
      'color-iactive-overlay-negative-selected-enabled':
        'var(--clr-iactive-overlay-negative-selected-enabled)',
      'color-iactive-overlay-negative-selected-hover':
        'var(--clr-iactive-overlay-negative-selected-hover)',
      'color-iactive-overlay-negative-selected-pressed':
        'var(--clr-iactive-overlay-negative-selected-pressed)',
      'color-iactive-overlay-inverse-enabled':
        'var(--clr-iactive-overlay-inverse-enabled)',
      'color-iactive-overlay-inverse-hover':
        'var(--clr-iactive-overlay-inverse-hover)',
      'color-iactive-overlay-inverse-pressed':
        'var(--clr-iactive-overlay-inverse-pressed)',
      'color-iactive-overlay-inverse-selected-enabled':
        'var(--clr-iactive-overlay-inverse-selected-enabled)',
      'color-iactive-overlay-inverse-selected-hover':
        'var(--clr-iactive-overlay-inverse-selected-hover)',
      'color-iactive-overlay-inverse-selected-pressed':
        'var(--clr-iactive-overlay-inverse-selected-pressed)',
    },
  },
  future: {
    hoverOnlyWhenSupported: true,
  },
  plugins: [
    require('prettier-plugin-tailwindcss', require('tailwindcss-animate')),
  ],
};
