/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        'family-inter': 'var(--font-inter)',
      },
      colors: {
        'color-primary': 'var(--color-primary)',
        'color-primary-light': 'var(--color-primary-light)',
        'color-secondary': 'var(--color-secondary)',
        'color-grey-005': 'var(--color-grey-005)',
        'color-grey-100': 'var(--color-grey-100)',
        'color-grey-200': 'var(--color-grey-200)',
        'color-grey-300': 'var(--color-grey-300)',
        'color-grey-400': 'var(--color-grey-400)',
        'color-grey-500': 'var(--color-grey-500)',
        'color-grey-600': 'var(--color-grey-600)',
        'color-grey-700': 'var(--color-grey-700)',
        'color-grey-800': 'var(--color-grey-800)',
        'color-grey-900': 'var(--color-grey-900)',
        'color-grey-950': 'var(--color-grey-950)',
        'color-pink-005': 'var(--color-pink-005)',
        'color-pink-100': 'var(--color-pink-100)',
        'color-pink-200': 'var(--color-pink-200)',
        'color-pink-300': 'var(--color-pink-300)',
        'color-pink-400': 'var(--color-pink-400)',
        'color-pink-500': 'var(--color-pink-500)',
        'color-pink-600': 'var(--color-pink-600)',
        'color-pink-700': 'var(--color-pink-700)',
        'color-pink-800': 'var(--color-pink-800)',
        'color-pink-900': 'var(--color-pink-900)',
        'color-pink-950': 'var(--color-pink-950)',
        'color-blue-005': 'var(--color-blue-005)',
        'color-blue-100': 'var(--color-blue-100)',
        'color-blue-200': 'var(--color-blue-200)',
        'color-blue-300': 'var(--color-blue-300)',
        'color-blue-400': 'var(--color-blue-400)',
        'color-blue-500': 'var(--color-blue-500)',
        'color-blue-600': 'var(--color-blue-600)',
        'color-blue-700': 'var(--color-blue-700)',
        'color-blue-800': 'var(--color-blue-800)',
        'color-blue-900': 'var(--color-blue-900)',
        'color-blue-950': 'var(--color-blue-950)',
        'color-cyan-005': 'var(--color-cyan-005)',
        'color-cyan-100': 'var(--color-cyan-100)',
        'color-cyan-200': 'var(--color-cyan-200)',
        'color-cyan-300': 'var(--color-cyan-300)',
        'color-cyan-400': 'var(--color-cyan-400)',
        'color-cyan-500': 'var(--color-cyan-500)',
        'color-cyan-600': 'var(--color-cyan-600)',
        'color-cyan-700': 'var(--color-cyan-700)',
        'color-cyan-800': 'var(--color-cyan-800)',
        'color-cyan-900': 'var(--color-cyan-900)',
        'color-cyan-950': 'var(--color-cyan-950)',
        'color-green-005': 'var(--color-green-005)',
        'color-green-100': 'var(--color-green-100)',
        'color-green-200': 'var(--color-green-200)',
        'color-green-300': 'var(--color-green-300)',
        'color-green-400': 'var(--color-green-400)',
        'color-green-500': 'var(--color-green-500)',
        'color-green-600': 'var(--color-green-600)',
        'color-green-700': 'var(--color-green-700)',
        'color-green-800': 'var(--color-green-800)',
        'color-green-900': 'var(--color-green-900)',
        'color-green-950': 'var(--color-green-950)',
        'color-yellow-005': 'var(--color-yellow-005)',
        'color-yellow-100': 'var(--color-yellow-100)',
        'color-yellow-200': 'var(--color-yellow-200)',
        'color-yellow-300': 'var(--color-yellow-300)',
        'color-yellow-400': 'var(--color-yellow-400)',
        'color-yellow-500': 'var(--color-yellow-500)',
        'color-yellow-600': 'var(--color-yellow-600)',
        'color-yellow-700': 'var(--color-yellow-700)',
        'color-yellow-800': 'var(--color-yellow-800)',
        'color-yellow-900': 'var(--color-yellow-900)',
        'color-yellow-950': 'var(--color-yellow-950)',
        'color-red-005': 'var(--color-red-005)',
        'color-red-100': 'var(--color-red-100)',
        'color-red-200': 'var(--color-red-200)',
        'color-red-300': 'var(--color-red-300)',
        'color-red-400': 'var(--color-red-400)',
        'color-red-500': 'var(--color-red-500)',
        'color-red-600': 'var(--color-red-600)',
        'color-red-700': 'var(--color-red-700)',
        'color-red-800': 'var(--color-red-800)',
        'color-red-900': 'var(--color-red-900)',
        'color-red-950': 'var(--color-red-950)',
      },
    },
  },
  future: {
    hoverOnlyWhenSupported: true,
  },
  plugins: [
    require('prettier-plugin-tailwindcss'),
    require('tailwindcss-animate'),
  ],
};
